CREATE TABLE IF NOT EXISTS bids (
  id SERIAL PRIMARY KEY,
  item_name VARCHAR(255) NOT NULL,
  bid_amount DECIMAL NOT NULL,
  bidder_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
